### PR TITLE
added info on creating java action

### LINKED ISSUE #96: Add documentation on how to add new Java action

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #96

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
Still working this one out.  @mihaitusa can you take a look and let me know what you think.

**Comment by mihaitusa** [comment]
@SamMarkowitz  Well, it looks good so far. I think it should be enough. At this point everyone can take a look upon score-actions and see what is in there regarding the `@actions` 
@gituser173 can you please take a look to?

**Comment by gituser173** [comment]
Nice, it looks good :+1:

**Comment by SamMarkowitz** [comment]
Alright then. I'll move this to ready to merge.

**Pull request merged**
