### PR TITLE
added python limitations

### LINKED ISSUE #15: Tutoriel - Specify requirements for running Python actions
Hello,

It would be good to improve the documentation for adding Python current limitation on CloudSlang platform.
Cython not supported
Python 3 not supported
How to check if you run a Cython dependency library

" we are supporting Python 2.7 (no 3), and we have a limitation that we do not support Python libs that need CPython (It's a Jython limitation actually)...
Need to check if your libs are using CPython..."

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #15 

Signed-off-by: Sam Markowitz sam.markowitz@hp.com

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
I'm not 100% we mean CPython and not Cython. Could someone who knows what their talking about please check.

**Comment by meirwah** [comment]
CPython.

http://www.jython.org/

image

Hopefully I know what I'm talking about...

**Comment by meirwah** [comment]
As you see there is some CPython support in Jython.. so maybe write this more accurate , that we support all that is supported by Jython?

**Comment by SamMarkowitz** [comment]
Changed the wording around.

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
