### PR TITLE
updated links to 0.9.60

### PR DESCRIPTION
**Pull request by SamMarkowitz**

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
Waiting for confirmation that master was first merged in v0.9.60.

**Comment by SamMarkowitz** [comment]
@Bonczidai are your sure master was merged into 0.9.60? Take a look at the diff for tutorials/lesson_11. I see stuff that already changed in the master that for some reason are showing as changes here as well.

**Comment by levice14** [comment]
weird, everything looks good in the commit history:
- https://github.com/CloudSlang/docs/commits/v0.9.60
- https://github.com/CloudSlang/docs/commits/master

**Comment by SamMarkowitz** [comment]
Well then, I think you can go ahead, review, and merge if everything looks fine. I will review the published output to make sure it's all okay.

**Comment by levice14** [comment]
:+1:

**Pull request merged**
