### PR TITLE
aligned to double quoting fix

### PR DESCRIPTION
**Pull request by SamMarkowitz**
waiting for merge of CloudSlang/cloud-slang#354

Signed-off-by: Sam Markowitz sam.markowitz@hp.com

### CODE REVIEW

**Comment by meirwah** [comment]
so we need to wait for the PR in Cloudslang BEFORE we merge this + do we have versions in ReadTheDocs to put this under 0.9dev  tab ??

**Comment by SamMarkowitz** [comment]
We can leave it in master for now which will show up as the "latest" version in ReadTheDocs.

**Comment by SamMarkowitz** [comment]
Not worth using this one after the change to reStructuredText. Closing this one, and opening a new one.

**Comment by SamMarkowitz** [comment]
Don't delete the branch just yet.

**Pull request closed without merging**
